language: node_js
node_js:
- "9"
dist: trusty
sudo: required

branches:
  only:
  - master

before_install:
- export TZ=Africa/Nairobi
- npm install -g @angular/cli
- npm install -g netlify-cli

script:
- ng lint
- ng test --watch=false --code-coverage=true --browsers=ChromeHeadless
- ng build --prod

after_script:
- bash <(curl -s https://codecov.io/bash)

addons:
  apt:
    packages:
    - google-chrome-stable

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -a $NETLIFY_AUTH_TOKEN -p -d ./dist/ng-weather
  skip-cleanup: true
  on:
    branch: master

codecov:
  token: $CODECOV_TOKEN