language: node_js
node_js:
- "9"
dist: trusty
sudo: required

branches:
  only:
  - master

before_install:
- npm install -g @angular/cli

script:
- npm run lint
- npm run test
- npm run build-prod

deploy:
  provider: firebase
  token:
    secure: "PHZHTIdO4aMSlvq8tU/9tEDwyXppXBW5BL6xOdQGHbOT6vAkbb1Bo+s2vpMMKI//wMiiDfcV6qfX3NUls+tLJaSzDjjWe2RSXuHfzlZSH2ifsf/U767pY97YFLmHZSOG8nZeeMEubkCjoYxMQRPmW0r0s5R1u7u6vq/4WFwrxFh1hHDpAZVbEVtxzEt4GKkYqs7lEG4nacq9VpMHapnD5uJj7z7F8CYXuycmscl+tcJCLp6efaKHo0v8QK56+s5h7QRvmV1jM5Cj9zoQ4uLH4WAu3++55+QSs2viYUDqROkgdJTO2+SpamMDfQOI1M0oOhO8R5Y6Wsof0UM1j49hLSbqE4d85ZbMLoosVKebJDTxTgIYgta0Ojhny8mBCG3di3s7WYI+vEZFL0tdok9cSB3XA/BpDzRKyJDRQt23pmjlc1fBR5upr0OSPVmIhsxL4cTTm2X346uXf+0YoM4f1jiKHM2SrmgfGbE3LiHUluHmYumlpIHqjijlQxhNeB3fwZ9WH2ti3WOJQh0gtWvXJMFdqjB3W/vVMo18QXYQoQRQL4GIUbdPVUHuaHyXM9WWTzXrSJYSPEvMlEBu5vNk1yx3nokxroMbhV7U/rPDWYWZUhvn904Mz4XxArFcx0axlcciCg7k+Uv9Na8oYOynOoBtd3EU2ZWARRiYmjqyWAo="