language: node_js
node_js:
- "9"
dist: trusty
sudo: required

branches:
  only:
  - master

before_install:
- export TZ=Africa/Nairobi
- npm install -g @angular/cli
- npm install -g firebase-tools

script:
- ng lint
- ng test --watch=false  --code-coverage=true --browsers=ChromeHeadless
- ng build --prod

after_script:
- bash <(curl -s https://codecov.io/bash)

addons:
  apt:
    packages:
    - google-chrome-stable

deploy:
  provider: firebase
  skip-cleanup: true
  token: $SECURE_TOKEN

codecov:
  token: $CODECOV_TOKEN