language: node_js
node_js:
- "9"
dist: trusty
sudo: required

branches:
  only:
  - master

before_install:
- export TZ=Africa/Nairobi
- npm install -g @angular/cli
- npm install -g firebase-tools

script:
- ng lint
- npm run test-headless
- ng build --prod

addons:
  apt:
    packages:
    - google-chrome-stable

deploy:
  provider: firebase
  skip-cleanup: true,
  token:
    secure: "J+k2t+9v/LplzxXlzgANTQeDlKiCeKTz3QCmPd0oHLzeshW94EYZl8K+qbS0dsdeC64Pu9oAlkbEpN8IqcrriJGc8dV1ThV1ofLr9Ag+AQsTpd4jmxWQkVpHFBEFO91Y2qPt59GxQ+tGnIRHJnNaV5UQJlPhICNIvuNioFaJLMq8+r8k7K4omR0vlN6f0owaM8/bCTvV4q/C1YKZaOTcnX+TMHvLNL63gwGwXZ+LJcv2FdW2Zm1yAJLUjEWmwN2iEKSU8l6jl0GZxG9COjj/cONb1Cyp5x0lKYjNjD2rXQY4izfkGv33Ln8gy1haWL9BkIbL0/FcUvGgFWHU1NAKpK3x/gySlZJ5XgSzTYP6bz0POpIgzUfbxROD2J/19yTo4OBV4+vyWZwUVuVi4NVQce8I4X8Vgc5cT67+CJF2ivI2t4q4epvc+W7FscxD9pSCu+O+rW3ZUwdd9jNtsU+2Yq/w+b0Su2Y6iJojbLNfTHPIwGogn2/fSRRI0iJXjqnClWuJXarA6ClhyMh6NRh3qUPpQvLyhH0EaJT6XTsar8VUUS86nYpsYkJRBrxRDrIE7Z1aLKVtL28TiY2M0Y7U5FP3jO1M8KRk6RTZ0HskZXvm1/CDR5cEKa+C71yn0TJq1RBu5rhtyWomJp2sCj3HdCldWdxK6h3bF8EiJ3Cs0bE="