language: node_js
node_js:
- "9"
dist: trusty
sudo: required

branches:
  only:
  - master

before_install:
- export TZ=Africa/Nairobi
- npm install -g @angular/cli
- npm install -g firebase-tools

script:
- ng lint
- npm run test-headless
- ng build --prod

addons:
  apt:
    packages:
    - google-chrome-stable

deploy:
  provider: firebase
  skip-cleanup: true,
  token: $SECURE_TOKEN